# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02d1f1dacd5dbc575a9c62d3201176fff8287ae369c901f33de9a2a5bd5c5976f340f6d175897feff93fee6a15383ee1378dde9043a4f4a212c46f1e023f193a

test:
  secret_key_base: b18a793e9e064177cc278e4605f2ee524b7f3954bf438097eadb144dd923b0320bd7a9387501921e4fedd0cb41e9fc164d67abdc5862596f4e7971ab08ac294c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
